// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv2l9CNSu-64wZPnhcLubV1KWIVkJ9Hgk',
    appId: '1:433084305338:web:20f776aefcd4fd83d15783',
    messagingSenderId: '433084305338',
    projectId: 'calmreminder',
    authDomain: 'calmreminder.firebaseapp.com',
    storageBucket: 'calmreminder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpyF-eG84_hEtuDljr-Eo0r4loZwoEarQ',
    appId: '1:433084305338:android:b1cc5ce93235288ed15783',
    messagingSenderId: '433084305338',
    projectId: 'calmreminder',
    storageBucket: 'calmreminder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO57mtxcX2if-iaGx3cazxU_cu8eLyST4',
    appId: '1:433084305338:ios:fb52c6b81dd4e3b7d15783',
    messagingSenderId: '433084305338',
    projectId: 'calmreminder',
    storageBucket: 'calmreminder.firebasestorage.app',
    iosBundleId: 'com.example.calmreminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO57mtxcX2if-iaGx3cazxU_cu8eLyST4',
    appId: '1:433084305338:ios:fb52c6b81dd4e3b7d15783',
    messagingSenderId: '433084305338',
    projectId: 'calmreminder',
    storageBucket: 'calmreminder.firebasestorage.app',
    iosBundleId: 'com.example.calmreminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv2l9CNSu-64wZPnhcLubV1KWIVkJ9Hgk',
    appId: '1:433084305338:web:aaae3f7cee068888d15783',
    messagingSenderId: '433084305338',
    projectId: 'calmreminder',
    authDomain: 'calmreminder.firebaseapp.com',
    storageBucket: 'calmreminder.firebasestorage.app',
  );
}
